version: '3'
services:
  mongo:
    image: mongo:3.6
  frontend:
    build:
      context: ./studybuddy
      dockerfile: Dockerfile
    image: gcr.io/gleaming-idiom-343203/sb_frontend
    command: npm start
    depends_on:
      - backend
    ports: 
      - "3000:3000"  
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: gcr.io/gleaming-idiom-343203/sb_backend
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     