kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}_backend
spec:
  selector:
    app: ${PROJECT_NAME}_backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}_backend
  labels:
    app: ${PROJECT_NAME}_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}_backend
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}_backend
    spec:
      containers:
      - name: ${PROJECT_NAME}_backend
        image: gcr.io/${GOOGLE_PROJECT_ID}/${BACKEND}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}_frontend
spec:
  selector:
    app: ${PROJECT_NAME}_frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}_frontend
  labels:
    app: ${PROJECT_NAME}_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}_frontend
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}_frontend
    spec:
      containers:
      - name: ${PROJECT_NAME}_frontend
        image: gcr.io/${GOOGLE_PROJECT_ID}/${FRONTEND}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP          