kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}-backend
spec:
  selector:
    app: ${PROJECT_NAME}-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}-backend
  labels:
    app: ${PROJECT_NAME}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-backend
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-backend
    spec:
      containers:
      - name: ${PROJECT_NAME}-backend
        image: gcr.io/${GOOGLE_PROJECT_ID}/${BACKEND}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}-frontend
spec:
  selector:
    app: ${PROJECT_NAME}-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}-frontend
  labels:
    app: ${PROJECT_NAME}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-frontend
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-frontend
    spec:
      containers:
      - name: ${PROJECT_NAME}-frontend
        image: gcr.io/${GOOGLE_PROJECT_ID}/${FRONTEND}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP          